### ISSUE TITLE
gcc-5 compiler support on Travis-CI

### ISSUE THREAD

**Issue by cggos** [GaoHongchen/PTAM-linux#1]
when I built this project on Travis-CI, I got errors of using deleted functions. After I search it on the Internet,I found it failed beacause of the wrong version of gcc/g++ and it should use gcc-5 to build. At the same time, I also found by the Travis-CI log that it was gcc-4.8 which was used to buid the project. So I had to set the compiler gcc-5.  
I added the following code from the Internet to file .travis.yml. 
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-5 g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```
But it did NOT make a good job !!!

**Comment by cggos** [comment]
I removed above code and added the following code. It really worked well !!!
```
sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - g++ --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
```
